work version
Victoria9Bob/VikaQase pull request #1
Opened 2022-02-12 15:33 UTC by Victoria9Bob

Посмотри, пожалуйста, проект. Особенно ApiDefectTest, так и не получилось массив объектов создать так, чтобы не ругалось. 
CI подключу чуть позже. Спасибо

2022-02-12 21:40 UTC, voropa commented
.idea и .iml файлы должны быть в .gitignore, так как это настройки твоей среды разработки

2022-02-13 17:11 UTC, voropa requested changes

2022-02-13 17:11 UTC, voropa commented on src/test/java/Adapters/BaseAdapter.java
> +    final String AUTRTH_TOKEN = "74d33400e63f102e391e5e1bc8cb9d365cd9d350";
Такие вещи как токен и логин/пароль лучше хранить и читать из .ocnfig файла, так как это давольно секьюрные данные и плохо, когда они лежат в коде в public репозитории на github

2022-02-13 17:11 UTC, voropa commented on src/test/java/Adapters/BaseAdapter.java
> +    final String AUTRTH_TOKEN = "74d33400e63f102e391e5e1bc8cb9d365cd9d350";
Вот тут я показывал  пример, как это сделать
https://docs.google.com/presentation/d/18CuJJrbIL2JbnZvoHOvA9Qw2JV97TLEhZSxj6LuV_UE/edit#slide=id.ga668f9158c_0_29

2022-02-13 17:11 UTC, voropa commented on src/test/java/Elements/BaseElement.java
> +            Thread.sleep(500);
Плохо использовать thread.sleep() и зачем он т тут вообще?

2022-02-13 17:11 UTC, voropa commented on src/test/java/Elements/Drobdown.java
> +    final String drobdownLOC = "//*[text()='%s']/ancestor::div/div/div[contains(@class,'notranslate')]";
Не очень хорошее название переменных, точнее оно не соответсвует java code convention. Имена переменных должны быть в camelCase, т.е dropdownLoc, а вообще "Loc" не очень хорошее сокращение для locator. так что лучше не полениться и дописать слово locator полность)
Да, и droPdown, а не droBdown.

2022-02-13 17:11 UTC, voropa commented on src/test/java/Elements/Drobdown.java
> +        log.info(String.format("Select an option: %s", optionName));
Я как-то говорил, что логи нужно  писать перед  действием, а не после него, чтобы в случае падения теста было понятно на каком шаге он  упал

2022-02-13 17:11 UTC, voropa commented on src/test/java/Elements/EditSuiteElement.java
> +    final String drobdownLOC = "css-io3r9z-singleValue";
Выглядит как не очень надежный локатор...

2022-02-13 17:11 UTC, voropa commented on src/test/java/Elements/FormatedTextElement.java
> +        log.info(String.format("Take value from %s", label));
Вот тут уже нарушается принцип абстракции при использовании классов-декораторов. 
FormatedTextElement должен работать уметь работать с любым элементом, у которого схожий локатор и схожее поведение и наоборот, любой элемент на странице, у которого схожий локатор и поведение может быть обернут в FormatedTextElement.
Так что методы getValue(), getVisibleText(), getTitleText() отлично под это подпадают и теоретически у любого элемента они могут быть вызваны.
А вот методы getSuiteName() и getStepText() нарушают этот принцип, так как они применимы только для каких-то определенных suite и step элементов и вряд ли  применимы для любых других элементов, обернутых в FormatedTextElement.
Так что тебе нужно либо пересмотреть элементы и локаторы и либо сделать еще отдельные декораторы для suite и step элементов, либо адаптировать их таким образом, чтобы getSuiteName и getStepText получались через общие getValue() или getVisibleText() методы

2022-02-13 17:11 UTC, voropa commented on src/test/java/Elements/Input.java
> +    @Step("Setting {text} into step input")
То же самое тут, нарушается абстрактность Input декоратора

2022-02-13 17:11 UTC, voropa commented on src/test/java/Modals/CaseDetailsModal.java
> +        Case aCase = new Case();
Что за странное название переменной? 
Лучше называт ьтакие вещи через result, например resultCase

2022-02-13 17:11 UTC, voropa commented on src/test/java/Modals/CaseModal.java
> +    @Step("Fill form.")
Весьма неинформативное описание step'a. Лучше добавить хотя бы название формы, которая заполняется

2022-02-13 17:11 UTC, voropa commented on src/test/java/Modals/CaseModal.java
> +    public RepositoryPage saveCaseButton() {
Названия методов должны быть глаголами, обозначающими какое-то действие, а в твоем случае это имена существительные. Так что должно быть, например, clickSaveCaseButton вместо saveCaseButton. 
ниже то же самое. И проверь во всех остальных page-классах

2022-02-13 17:11 UTC, voropa commented on src/test/java/Models/Case.java
> +                Objects.equals(expectedResult, aCase.expectedResult);
Методы equals and hasCode генерируются автоматически при помощи аннотации @Data
А для конструктора есть анотация @AllArgConstructor
Так что можно заметит эти 100 строчек кода на 2 аннотации)

2022-02-13 17:11 UTC, voropa commented on src/test/java/Models/SelectTestCases.java
> +package Models;
пустой класс, удали его, если он нигде не используется

2022-02-13 17:11 UTC, voropa commented on src/test/java/Models/Suite.java
> +    public Suite(String suiteName, SuiteParentSuite parentSuite, String description, String preconditions) {
То же самое тут, можно заменить на @Data и @AllArgConstructor

2022-02-13 17:11 UTC, voropa commented on src/test/java/Pages/LoginPage.java
> +    @Link(BASE_URL)
C помощью аннотаций @Link в allure обычно прикрепляют ссылки на какой-нибудь дефект или задачу из project management системы, а не указывают url страницы, на  которой сейчас выполняется тест. 
Так что ты их тут неправильно используешь и они излишние.

2022-02-13 17:11 UTC, voropa commented on src/test/java/Pages/ProjectsPage.java
> +    protected final static String ProjectsURL = "https://app.qase.io/projects";
константы должны быть написаны в UPPER_CASE

2022-02-13 17:11 UTC, voropa commented on src/test/java/Pages/RepositoryPage.java
> +    private String EDIT_SUITE = "//span[contains(text(),'%s')]//following::button[2]";
Плохие локаторы с порядковыми номерами внутри типа button[2], лучше исправить

2022-02-13 17:11 UTC, voropa commented on src/test/java/Tests/CreateCaseTest.java
> +    public void createCaseWithAllData() throws InterruptedException {
Так  как в этом классе всего один тестовый метод, то можно для красоты вынести создание тестовых данных в BeforeMethod, а удаление тестовых данных в AfterMethod

2022-02-13 17:11 UTC, voropa commented on src/test/java/Tests/CreateSuiteTest.java
> +    public void createSuiteWithAllData() throws InterruptedException {
То же самое с before и after method

2022-02-13 17:11 UTC, voropa commented on src/test/java/Tests/TestListener.java
> +//        File distfile = new File("/D:/Qase/target/"+result.getName()+".scr.jpg");
Почему тут закоментированный код? либо удали его, либо раскоментируй

2022-02-13 17:11 UTC, voropa commented on src/test/resources/allure.properties
> +allure.link.issue.pattern=https://instagram.com/{}
instagram?) он тут точно нужен?)

2022-02-13 17:11 UTC, voropa commented on src/test/resources/regression.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Почему только один suite.sml?
Я бы слелал как миниум 2:
в одном API тесты, в другом - UI тесты. Так как на реальных проектах чаще всего их запускают раздельно

2022-02-13 17:11 UTC, voropa commented on src/test/resources/config.properties
> +qase.username = enter your username here
Вот, у тебя же даже есть config.properties файл. Вот в него нужно вынеcти все sensetive данные, типа username/password и token

2022-02-13 19:01 UTC, voropa requested changes

2022-02-13 19:01 UTC, voropa commented on pom.xml
> +        <suiteXmlFile>src/test/resources/regression.xml</suiteXmlFile>
Ты уверена, что у тебя запускается именно regression.xml по команде mvn test? По-поему в конфигурации maven-surefire-plugin выше пропущен атрибут suiteXmlFile, а должен быть
<img width="503" alt="image" src="https://user-images.githubusercontent.com/14195681/153769434-292e5c02-c0c4-41f4-86e2-4bf2200c7cd9.png">

2022-02-13 19:01 UTC, voropa commented on src/test/java/Tests/ApiDefectTest.java
> +                custom_field(DefectCustomFields.builder().id("0").value("").build()).
Вот так работает
custom_field(Arrays.asList(DefectCustomFields.builder().id("0").value("").build())).
Плюс еще в Defect классе нужно поменять тип свойства custom_field на 
List<DefectCustomFields> custom_field;

По аналогии в строчке 61

2022-02-14 09:37 UTC, voropa requested changes

2022-02-14 09:37 UTC, voropa commented on src/test/java/Tests/ApiProjectTest.java
> +    createProjectPositiveTest() {
Этот тест падает у меня.
вероятно, проблема в том, что project code должен быть уникальным и система ругается:
    "errorFields": [
        {
            "field": "project",
            "error": "Project with the same code already exists."
        }
    ]

2022-02-14 09:37 UTC, voropa commented on src/test/java/Tests/ApiProjectTest.java
> +        String projectCode = "API";
А вот твой projectCode, который всегда одинаковый, вот и тест с ним может выполнится только один раз...
Так что нужно генерировать рандомный код, чтобы он прикаждом запуске был разный и тест всегда работал.
Библиотека java-faker тебе в помощь
https://github.com/DiUS/java-faker

2022-02-14 09:37 UTC, voropa commented on src/test/java/Tests/CreateCaseTest.java
> +public class CreateCaseTest extends BaseTest{
У меня этот тест не проходит, все время падает. Предполагаю, что где-то нужно добавить ожидание....

2022-02-16 17:13 UTC, Victoria9Bob commented
> Файлы .idea и .iml должны быть в .gitignore, так как это настройки вашей среды разработки

Добавила файлы target .idea *.iml .allure в .gitignore

2022-02-16 17:40 UTC, Victoria9Bob commented on src/test/resources/allure.properties
> +allure.link.issue.pattern=https://instagram.com/{}
Удалила)

2022-02-16 17:41 UTC, Victoria9Bob commented on src/test/java/Tests/ApiDefectTest.java
> +                custom_field(DefectCustomFields.builder().id("0").value("").build()).
Сработало, спасибо

2022-02-16 17:42 UTC, Victoria9Bob commented
> .idea и .iml файлы должны быть в .gitignore, так как это настройки твоей среды разработки

Добавила

2022-02-16 17:43 UTC, Victoria9Bob commented on pom.xml
> +        <suiteXmlFile>src/test/resources/regression.xml</suiteXmlFile>
Добавила

2022-02-16 17:44 UTC, Victoria9Bob commented on src/test/java/Tests/TestListener.java
> +//        File distfile = new File("/D:/Qase/target/"+result.getName()+".scr.jpg");
сделано)

2022-02-16 17:45 UTC, Victoria9Bob commented on src/test/java/Tests/CreateCaseTest.java
> +    public void createCaseWithAllData() throws InterruptedException {
Вынесла в классах CaseTest, SuiteTest, PlanTest

2022-02-16 17:46 UTC, Victoria9Bob commented on src/test/java/Tests/CreateSuiteTest.java
> +    public void createSuiteWithAllData() throws InterruptedException {
сделано

2022-02-16 17:46 UTC, Victoria9Bob commented on src/test/java/Pages/ProjectsPage.java
> +    protected final static String ProjectsURL = "https://app.qase.io/projects";
поправила модификаторы доступа и названия локаторов

2022-02-16 17:47 UTC, Victoria9Bob commented on src/test/java/Pages/LoginPage.java
> +    @Link(BASE_URL)
удалила ссылки в аннотациях

2022-02-16 17:47 UTC, Victoria9Bob commented on src/test/java/Models/Suite.java
> +    public Suite(String suiteName, SuiteParentSuite parentSuite, String description, String preconditions) {
заменила на аннотации и удалила лишние строчки кода

2022-02-16 17:48 UTC, Victoria9Bob commented on src/test/java/Models/SelectTestCases.java
> +package Models;
удалила

2022-02-16 17:48 UTC, Victoria9Bob commented on src/test/java/Models/Case.java
> +                Objects.equals(expectedResult, aCase.expectedResult);
сделано

2022-02-16 17:48 UTC, Victoria9Bob commented on src/test/java/Modals/CaseModal.java
> +    @Step("Fill form.")
сделала

2022-02-17 17:15 UTC, Victoria9Bob commented on src/test/java/Elements/Drobdown.java
> +        log.info(String.format("Select an option: %s", optionName));
Переставила

2022-02-17 17:41 UTC, Victoria9Bob commented on src/test/java/Modals/CaseDetailsModal.java
> +        Case aCase = new Case();
сделала

2022-02-17 17:49 UTC, Victoria9Bob commented on src/test/java/Modals/CaseModal.java
> +    public RepositoryPage saveCaseButton() {
поменяла названия

2022-02-17 18:58 UTC, Victoria9Bob commented on src/test/java/Tests/ApiProjectTest.java
> +        String projectCode = "API";
Добавила библиотеку и прописала данные в тестовых классах через нее. Отдельно класс генератор не создавала, т.к. перегружать метод с разными вариантами мне не нужно

2022-02-17 19:01 UTC, Victoria9Bob commented on src/test/java/Tests/ApiProjectTest.java
> +    createProjectPositiveTest() {
да, теперь генерит уникальный через Faker

2022-02-18 19:57 UTC, Victoria9Bob commented on src/test/resources/regression.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Сделала 3 API и 2 на UI(smoke, regression). Добавила группы

2022-02-19 05:25 UTC, Victoria9Bob commented on src/test/java/Tests/ApiDefectTest.java
> +                custom_field(DefectCustomFields.builder().id("0").value("").build()).
Но сами методы не работают все равно)

2022-02-19 06:33 UTC, Victoria9Bob commented on src/test/java/Elements/FormatedTextElement.java
> +        log.info(String.format("Take value from %s", label));
Создала отдельные классы-обертки, где это было нужно

2022-02-19 06:33 UTC, Victoria9Bob commented on src/test/java/Elements/Input.java
> +    @Step("Setting {text} into step input")
исправила

2022-02-19 06:41 UTC, Victoria9Bob commented on src/test/java/Elements/BaseElement.java
> +            Thread.sleep(500);
Убрала

2022-02-19 06:52 UTC, Victoria9Bob commented on src/test/java/Elements/EditSuiteElement.java
> +    final String drobdownLOC = "css-io3r9z-singleValue";
Поправила

2022-02-19 07:10 UTC, Victoria9Bob commented on src/test/java/Pages/RepositoryPage.java
> +    private String EDIT_SUITE = "//span[contains(text(),'%s')]//following::button[2]";
Убрала

2022-02-19 07:12 UTC, Victoria9Bob commented on src/test/java/Adapters/BaseAdapter.java
> +    final String AUTRTH_TOKEN = "74d33400e63f102e391e5e1bc8cb9d365cd9d350";
Этим сегодня займусь

2022-02-19 11:31 UTC, voropa requested changes
1. Прожми кнопку resolve для тех комантариев, которые ты уже исправила, чтобы они не висели открытыми
2. Пересмотри оставшиеся незакрытые коментарии + несколько новых
3. ОТДЕЛЬНЫМ КОМИТОМ в самом конце отформатируй весь проект, чтобы убрать лишние пробелы, отступы и т.д 
В IDEA это можно сделать автоматически:
<img width="464" alt="image" src="https://user-images.githubusercontent.com/14195681/154799016-e95c85a4-a084-4799-b5be-89f9ed64eb83.png">

2022-02-19 11:31 UTC, voropa commented on src/test/java/Pages/LoginPage.java
> +    @Link(BASE_URL)
А вот именно тут не удалила)

2022-02-19 11:31 UTC, voropa commented on src/test/java/Pages/LoginPage.java
> +    @Step("Open login page.")
Так у тебя же уже есть метод open() в этом классе. зачем тебюе еще один метод openLoginPage()??

2022-02-19 11:31 UTC, voropa commented on src/test/java/Pages/RepositoryPage.java
> +    protected final static String REPOSITORY_URL = "https://app.qase.io/project/DEMO?view=1&suite=2";
Думаю, что этот URL не сработает в 99% случаев, так как в нем указан код конкретного проекта.
Для таких страниц, которые зависят от какого-то обьекта и в URL имеют параметры этого обьекта, нет смысла делать метод open() через driver.get(URL). т.к. им нельзя воспользоваться в 99% случаев

2022-02-19 11:31 UTC, voropa commented on src/test/java/Pages/RepositoryPage.java
> +    //span[contains(text(),'%s')]//ancestor::h3//i[contains(@class,'pencil')]
удали закоментированный код

2022-02-19 11:31 UTC, voropa commented on src/test/java/Pages/TestPlansPage.java
> +    protected final static String TEST_PLANS_URL = "https://app.qase.io/plan/DEMO";
то же самое тут, у тебя TestPlansPage привязывается к проекту, который ты открываешь, так что нельзя попасть на эту страницу по URL

2022-02-19 11:31 UTC, voropa commented on src/test/java/Tests/CreateCaseTest.java
> +        Assert.assertTrue(isloggedIn);
В before/After методах не должно быть проверок, проверки должны быть только  в тестах

2022-02-19 11:31 UTC, voropa commented on src/test/java/Tests/CreateSuiteTest.java
> +        Assert.assertTrue(isloggedIn);
То же самое

2022-02-19 11:31 UTC, voropa commented on src/test/java/Elements/EditSuiteElement.java
> +    public String getDropdownSuiteValue() {
Какой смысл от этого метода, если он не зависит ни от label'a в этом классе и сам локатор не параметризированный. По факту этот локатор ищет любой dropdown на любой странице, так что думаю, что ему не место в этом классе-обертке

2022-02-19 11:31 UTC, voropa commented on .gitignore
> +target
Все эти фалы все еще попадают в пулл реквест.
Вероятно не совсем правильно указаны пути в .gitignore
Должно быть как то так
/.idea
/target
/.allure
/.allure-results
*.iml

2022-02-19 15:47 UTC, voropa commented
Еще общее замечание: названия пакетов (Tests, Pages, Enums, ...) в java должны быть с маленькой буквы

2022-02-20 06:00 UTC, Victoria9Bob commented on src/test/java/Adapters/BaseAdapter.java
> +    final String AUTRTH_TOKEN = "74d33400e63f102e391e5e1bc8cb9d365cd9d350";
теперь читает через property reader

2022-02-20 06:01 UTC, Victoria9Bob commented on src/test/resources/config.properties
> +qase.username = enter your username here
теперь читает через property reader

2022-02-20 06:07 UTC, Victoria9Bob commented on src/test/java/Pages/LoginPage.java
> +    @Step("Open login page.")
Уже удалила) Потому что у меня для логина и создания пользователя url разные и чтобы не делать лишних действий и искать нужные страницы, сразу по url перехожу.

2022-02-20 06:08 UTC, Victoria9Bob commented on src/test/java/Pages/LoginPage.java
> +    @Step("Open login page.")
Ты вроде говорил, что так можно

2022-02-20 06:12 UTC, Victoria9Bob commented on src/test/java/Pages/RepositoryPage.java
> +    protected final static String REPOSITORY_URL = "https://app.qase.io/project/DEMO?view=1&suite=2";
Так мне и нужен конкретный проект, потому что в противном случае мне нужно создавать новый проект перед каждым тестом, что увеличивает время каждого теста. Поэтому я использую тестовый проект, а создание проектов проверяю отдельными тестами через api.

2022-02-20 06:12 UTC, Victoria9Bob commented on src/test/java/Pages/RepositoryPage.java
> +    //span[contains(text(),'%s')]//ancestor::h3//i[contains(@class,'pencil')]
удалила

2022-02-20 06:37 UTC, Victoria9Bob commented on src/test/java/Pages/LoginPage.java
> +    @Link(BASE_URL)
готово

2022-02-20 06:40 UTC, Victoria9Bob commented on .gitignore
> +target
поправила

2022-02-20 07:31 UTC, voropa commented on src/test/java/Pages/RepositoryPage.java
> +    protected final static String REPOSITORY_URL = "https://app.qase.io/project/DEMO?view=1&suite=2";
Да, но конкретный проект - это часть  тестовых данных, а тестовые данные должны быть в тестах, а не захардкоданы в пэйджах. Пэйджы - это абстрактные классы, которые должны работать с любыми данными...
В таком случае тебе нужно хранить название тестового проекта где-то в тестах и открывать его каким-то методом типа homePage.openProject(testProjectName)

2022-02-20 07:32 UTC, voropa commented on src/test/java/Pages/LoginPage.java
> +    @Step("Open login page.")
Очень вряд ли. Если используется loadablePage паттерн, то метод open() в каждой странице должен быть определен однозначно...

2022-02-20 07:38 UTC, voropa commented on src/test/java/Pages/RepositoryPage.java
> +    protected final static String REPOSITORY_URL = "https://app.qase.io/project/DEMO?view=1&suite=2";
Т.е. у тебя должна быть страница,  н которую ты попадаешь после авторизации, и уже на ней ты кликаешь на нужный проект. Тогда открывается RepositoryPage с проектом
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/14195681/154833160-d97df0f4-8654-4033-82aa-16f4e441f236.png">

loginPage.login();
//now you're at homePage
homePage.openProject(projectName);
//now you're at project repositoryPage
repositoryPage.doSomeAtcions()......

2022-02-20 08:57 UTC, Victoria9Bob commented on src/test/java/Pages/RepositoryPage.java
> +    protected final static String REPOSITORY_URL = "https://app.qase.io/project/DEMO?view=1&suite=2";
Я понимаю, о чем ты говоришь. А можно оставить переход по url, но id проекта вынести отдельно в base класс и переопределяя метод open() как бы собирать нужный url, таким образом, если мне нужно зайти в другой проект, я меняю только одну переменную. Показала отдельным комитом.

2022-02-20 09:21 UTC, Victoria9Bob commented on src/test/java/Elements/EditSuiteElement.java
> +    public String getDropdownSuiteValue() {
Убрала

2022-02-20 09:21 UTC, Victoria9Bob commented on src/test/java/Tests/CreateCaseTest.java
> +        Assert.assertTrue(isloggedIn);
Перекинула в тесты

2022-02-20 09:21 UTC, Victoria9Bob commented on src/test/java/Tests/CreateSuiteTest.java
> +        Assert.assertTrue(isloggedIn);
сделала

2022-02-20 09:29 UTC, voropa commented on src/test/java/Pages/RepositoryPage.java
> +    protected final static String REPOSITORY_URL = "https://app.qase.io/project/DEMO?view=1&suite=2";
Да, так теретически тоже можно, это будет хотя бы правильно с точки зрения архитектуры. Метод open() должен получать на вход id проекта и формировать динамический URL.
Но на будущее правильнее делать так, как я писал  выше, потому что selenium тесты должны эмулировать действия пользователя, а пользователь вряд ли будет открывать проект через адреснуб строку, он скорее будет кликать на иконку на UI)

Соответсвенно переделай метод open() во всех классах-страницах, где в URL есть id проекта

2022-02-20 09:29 UTC, Victoria9Bob commented on src/test/java/Pages/RepositoryPage.java
> +    protected final static String REPOSITORY_URL = "https://app.qase.io/project/DEMO?view=1&suite=2";
Т.е. в каждом тесте все равно идет логин и открывается страница проектов, просто вместо действия кликнуть на проект(DEMO), я открываю его url, а не по локатору, со страницей test plans вместо кликнуть на проект, кликнуть на тест план - сразу открываю тест план))

2022-02-20 18:00 UTC, Victoria9Bob commented on src/test/java/Tests/ApiDefectTest.java
> +                custom_field(DefectCustomFields.builder().id("0").value("").build()).
Поправила тесты, они работают, но тест на создание дефекта возвращает только один параметр -id. Он его присваивает сам каждый раз новый и получается, что тест одноразовый) Нужно вручную выставлять ожидаемый id. Не знаю, как от этого уйти(

2022-02-20 18:01 UTC, Victoria9Bob commented on src/test/java/Pages/LoginPage.java
> +    @Step("Open login page.")
поправила

2022-02-20 18:01 UTC, Victoria9Bob commented on src/test/java/Pages/RepositoryPage.java
> +    protected final static String REPOSITORY_URL = "https://app.qase.io/project/DEMO?view=1&suite=2";
поправила

2022-02-20 18:02 UTC, Victoria9Bob commented on src/test/java/Pages/TestPlansPage.java
> +    protected final static String TEST_PLANS_URL = "https://app.qase.io/plan/DEMO";
поправила

2022-02-21 14:23 UTC, Victoria9Bob commented on src/test/java/Tests/ApiDefectTest.java
> +                custom_field(DefectCustomFields.builder().id("0").value("").build()).
готово

2022-02-21 15:28 UTC, voropa commented
Please resolve merge conflicts below

2022-02-21 21:32 UTC, voropa requested changes

2022-02-21 21:32 UTC, voropa commented on src/test/resources/config.properties
> +qase.repository_uri = /project
Эти пути незачем хранить в конфиг файле, они могут лежать прямо в page классе. В конфиг файле у тебя должен быть base_url и project_id.
А в page классах уже будет формироваться динамический URL, на основании этих параметров

2022-02-21 21:32 UTC, voropa commented on src/test/resources/config.properties
> +qase.email=bob123@mailinator.com
Все эти данные нужно убрать из property файла, перед тем, как мержить в master

2022-02-21 21:32 UTC, voropa commented on src/test/java/tests/CreateSuiteTest.java
> +//        Assert
Лишний коментарий

2022-02-21 21:32 UTC, voropa commented on src/test/java/tests/ApiDefectTest.java
> +package tests;//package Tests;
Так же лишнйи коментарий

2022-02-21 21:32 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    protected final static String PROJECT_ID = "/DEMO";
pROJECT_ID - это переменная, относящаяся к тестовым данным, а не к странице,  поэтому должна хранится скорее в BaseTest и передаваться в page в качестве входного аргумента в методах open()

2022-02-21 21:32 UTC, voropa commented on src/test/java/models/Defect.java
> +//    int milestone_id;
закоментированый код

2022-02-22 14:18 UTC, Victoria9Bob commented on src/test/resources/config.properties
> +qase.email=bob123@mailinator.com
заменила все данные в этом файле

2022-02-22 14:18 UTC, Victoria9Bob commented on src/test/java/tests/CreateSuiteTest.java
> +//        Assert
изменила

2022-02-22 14:19 UTC, Victoria9Bob commented on src/test/java/tests/ApiDefectTest.java
> +package tests;//package Tests;
убрала

2022-02-22 14:20 UTC, Victoria9Bob commented on src/test/java/models/Defect.java
> +//    int milestone_id;
убрала

2022-02-22 14:59 UTC, Victoria9Bob commented on src/test/java/pages/BasePage.java
> +    protected final static String PROJECT_ID = "/DEMO";
сделала

2022-02-22 15:00 UTC, merged